//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from RasaIntentExample.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IRasaIntentExampleListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
internal partial class RasaIntentExampleBaseListener : IRasaIntentExampleListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RasaIntentExampleParser.example"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExample([NotNull] RasaIntentExampleParser.ExampleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RasaIntentExampleParser.example"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExample([NotNull] RasaIntentExampleParser.ExampleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RasaIntentExampleParser.text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterText([NotNull] RasaIntentExampleParser.TextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RasaIntentExampleParser.text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitText([NotNull] RasaIntentExampleParser.TextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RasaIntentExampleParser.entityExample"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntityExample([NotNull] RasaIntentExampleParser.EntityExampleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RasaIntentExampleParser.entityExample"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntityExample([NotNull] RasaIntentExampleParser.EntityExampleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RasaIntentExampleParser.entityValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntityValue([NotNull] RasaIntentExampleParser.EntityValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RasaIntentExampleParser.entityValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntityValue([NotNull] RasaIntentExampleParser.EntityValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RasaIntentExampleParser.entityName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntityName([NotNull] RasaIntentExampleParser.EntityNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RasaIntentExampleParser.entityName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntityName([NotNull] RasaIntentExampleParser.EntityNameContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
