//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from RasaIntentExample.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="RasaIntentExampleParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.CLSCompliant(false)]
internal interface IRasaIntentExampleListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RasaIntentExampleParser.example"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExample([NotNull] RasaIntentExampleParser.ExampleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RasaIntentExampleParser.example"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExample([NotNull] RasaIntentExampleParser.ExampleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RasaIntentExampleParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterText([NotNull] RasaIntentExampleParser.TextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RasaIntentExampleParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitText([NotNull] RasaIntentExampleParser.TextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RasaIntentExampleParser.entityExample"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEntityExample([NotNull] RasaIntentExampleParser.EntityExampleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RasaIntentExampleParser.entityExample"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEntityExample([NotNull] RasaIntentExampleParser.EntityExampleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RasaIntentExampleParser.entityValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEntityValue([NotNull] RasaIntentExampleParser.EntityValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RasaIntentExampleParser.entityValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEntityValue([NotNull] RasaIntentExampleParser.EntityValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RasaIntentExampleParser.entityName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEntityName([NotNull] RasaIntentExampleParser.EntityNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RasaIntentExampleParser.entityName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEntityName([NotNull] RasaIntentExampleParser.EntityNameContext context);
}
