//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SkillExample.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.CLSCompliant(false)]
public partial class SkillExampleLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, WORD=3;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "WORD", "Letter"
	};


	public SkillExampleLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public SkillExampleLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'{{'", "'}}'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, "WORD"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "SkillExample.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static SkillExampleLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,3,32,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,1,0,1,0,1,0,1,1,1,1,1,1,
		1,2,4,2,17,8,2,11,2,12,2,18,1,3,1,3,1,3,1,3,1,3,4,3,26,8,3,11,3,12,3,27,
		1,3,3,3,31,8,3,0,0,4,1,1,3,2,5,3,7,0,1,0,6,6,0,36,36,45,45,48,57,65,90,
		95,95,97,122,2,0,0,127,55296,56319,1,0,55296,56319,1,0,56320,57343,3,0,
		9,10,13,13,32,32,6,0,34,35,37,38,44,44,46,46,58,59,63,63,36,0,1,1,0,0,
		0,0,3,1,0,0,0,0,5,1,0,0,0,1,9,1,0,0,0,3,12,1,0,0,0,5,16,1,0,0,0,7,30,1,
		0,0,0,9,10,5,123,0,0,10,11,5,123,0,0,11,2,1,0,0,0,12,13,5,125,0,0,13,14,
		5,125,0,0,14,4,1,0,0,0,15,17,3,7,3,0,16,15,1,0,0,0,17,18,1,0,0,0,18,16,
		1,0,0,0,18,19,1,0,0,0,19,6,1,0,0,0,20,31,7,0,0,0,21,31,8,1,0,0,22,23,7,
		2,0,0,23,31,7,3,0,0,24,26,7,4,0,0,25,24,1,0,0,0,26,27,1,0,0,0,27,25,1,
		0,0,0,27,28,1,0,0,0,28,31,1,0,0,0,29,31,7,5,0,0,30,20,1,0,0,0,30,21,1,
		0,0,0,30,22,1,0,0,0,30,25,1,0,0,0,30,29,1,0,0,0,31,8,1,0,0,0,4,0,18,27,
		30,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
